### ISSUE TITLE
Cache SDL builds

### ISSUE THREAD

**Issue by madebr** [madebr/setup-sdl#2]

**Comment by madebr** [comment]
This is implemented since caf33264642a3af89723f3b55f05436196460248,
but there is always a cache hit due to version mismatch.

I've asked at https://github.com/orgs/community/discussions/58342

**Comment by FtZPetruska** [comment]
This seems to be an issue with how `cache.restoreCache` works. It seems like the function should be given a copy of the paths to avoid version mismatch, as such:
```js
const found_cache_key = await cache.restoreCache(
  Array.from(CACHE_PATHS), // or CACHE_PATHS.slice()
  CACHE_KEY
);
```

See:
- https://github.com/bahmutov/npm-install/issues/175#issuecomment-1537032551
- https://github.com/actions/toolkit/issues/1376#issuecomment-1478076043

**Comment by madebr** [comment]
Many many thanks @FtZPetruska 
I've applied your suggestion in https://github.com/madebr/setup-sdl/commit/f9125121cc36c689d94cb1dcc3305d1cb45dfe54 and the action is now blazing fast!
Woohoo!
